Repository danielmiessler/SecLists, pull requests merged in 2021-11, with the labels that each got.

#668 Add IBM MQSeries common channel names
  Fuzzing/IBMMQSeries-channels.txt
Labels: enhancement

#666 Create hashicorp-vault.txt
  Discovery/Web-Content/hashicorp-vault.txt
Labels: enhancement

#649 Many more scopes, and cleanup of oauth-oidc-scopes.txt
  Discovery/Web-Content/oauth-oidc-scopes.txt
Labels: enhancement

#648 Fix row column quantity to 4
  Passwords/Default-Credentials/default-passwords.csv
Labels: bug

#640 adding "dismiss" to big.txt
  Discovery/Web-Content/big.txt
Labels: enhancement, help wanted

#633 Update nginx.txt
  Discovery/Web-Content/nginx.txt
Labels: enhancement, help wanted

#670 Add example c root-shells
  Miscellaneous/source-code/c-linux/Makefile
  Miscellaneous/source-code/c-linux/drop-shell.c
  Miscellaneous/source-code/c-linux/root-shell.c
  Miscellaneous/source-code/c-linux/root-shell2.c
  Miscellaneous/source-code/c-linux/root-shell3.c
  Miscellaneous/source-code/c-linux/tiny-shell.c
Labels: enhancement

#672 Add PURGE method
  Fuzzing/http-request-methods.txt
Labels: enhancement
