Repository danielmiessler/SecLists, pull requests merged in 2022-11, with the labels that each got.

#746 Fixed typo on line 26
  Discovery/Web-Content/reverse-proxy-inconsistencies.txt
Labels: proposal

#800 Add Github workflow to check for entries starting with "/".
  .bin/check-file-for-starting-slash
  .github/workflows/wordlist-validator_verify_entries_for_starting_with_slash.yml
Labels: enhancement, proposal

#807 [spring-boot.txt] Add new endpoints
  Discovery/Web-Content/spring-boot.txt
Labels: enhancement

#810 add site-editor and mail-masta to wp-plugins.fuzz.txt
  Discovery/Web-Content/CMS/wp-plugins.fuzz.txt
Labels: enhancement

#811 Create salesforce-aura-objects.txt
  Discovery/Web-Content/api/salesforce-aura-objects.txt
Labels: enhancement

#812 Create hashicorp-consul-api.txt
  Discovery/Web-Content/hashicorp-consul-api.txt
Labels: enhancement

#813 added new backupfiles in wordpress fuzz list
  Discovery/Web-Content/CMS/wordpress.fuzz.txt
Labels: enhancement

#815 Update CommonAdminBase64.txt
  Usernames/CommonAdminBase64.txt
Labels: enhancement

#804 Update js.txt
  Discovery/Web-Content/SVNDigger/cat/Language/js.txt
Labels: enhancement

#831 Update contributors (2022.4)
  CONTRIBUTORS.md
Labels: enhancement
