Repository danielmiessler/SecLists, pull requests merged in 2022-08, with the labels that each got.

#774 Add common Environment identifiers
  Fuzzing/environment-identifiers.txt
Labels: enhancement

#769 Fuzz amounts, quantities, or any other numerical values.
  Fuzzing/Amounts/README.md
  Fuzzing/Amounts/all.txt
  Fuzzing/Amounts/hundred.txt
  Fuzzing/Amounts/hundred_thousand.txt
  Fuzzing/Amounts/milion.txt
  Fuzzing/Amounts/one.txt
  Fuzzing/Amounts/ten.txt
  Fuzzing/Amounts/ten_thousand.txt
  Fuzzing/Amounts/thousand.txt
  Fuzzing/Amounts/zero.txt
  Fuzzing/Amounts/zero_point_one.txt
Labels: enhancement

#767 Update dirsearch.txt
  Discovery/Web-Content/dirsearch.txt
Labels: enhancement

#748 README.md: Added 'Cook' to related projects
  README.md
Labels: proposal

#713 ISPSystem BillManager - list of api endpoints for hostings penetration tests
  Discovery/Web-Content/api/ispsystem_billmanager_api.txt
Labels: enhancement

#706 Create country-codes.txt
  Fuzzing/country-codes.txt
Labels: enhancement

#702 Added devops extensions - .test, .qa., etc. to Fuzzing/extensions-Bo0oM.txt
  Fuzzing/extensions-Bo0oM.txt
Labels: enhancement

#701 Added more PHP web shells
  Discovery/Web-Content/CommonBackdoors-PHP.fuzz.txt
  Discovery/Web-Content/Oracle-EBS-wordlist.txt
Labels: enhancement

#777 Added awesome-environment-variable-names.txt and an auto-updater github action
  .github/workflows/wordlist-updater_awesome-list-of-secrets-in-environment-variables.yml
  Discovery/Variables/awesome-environment-variable-names.txt
Labels: enhancement

#796 Ready for 2022.3
  CONTRIBUTORS.md
  Passwords/README.md
  Passwords/url-to-download-passwords.md
  README.md
Labels: maintenance
