Repository danielmiessler/SecLists, pull requests merged in 2023-11, with the labels that each got.

#901 Update LFI-gracefulsecurity-linux.txt to include older SSH key format "ECDSA"
  Fuzzing/LFI/LFI-gracefulsecurity-linux.txt
Labels: enhancement

#882 more human injection; new LLM section
  Fuzzing/big-list-of-naughty-strings.txt
Labels: enhancement

#918 2023.4 release
  CONTRIBUTORS.md
  Discovery/Web-Content/web-extensions-big.txt
Labels: maintenance

#919 Updated os-names.txt and changed os-names-mutate.py
  .bin/os-names-mutate.py
  Fuzzing/os-names-mutated.txt
  Fuzzing/os-names.txt
Labels: bug, enhancement

#922 removed new line at the start
  Discovery/Web-Content/oracle.txt
Labels: bug

#925 set execute bit on all scripts and removed redundant commands
  .bin/check-file-for-starting-slash
  .bin/file-extensions-downloader.py
  .bin/generate-environment-identifiers-dict.sh
  .bin/os-names-mutate.py
  .github/workflows/wordlist-validator_verify_entries_for_starting_with_slash.yml
Labels: bug

#913 Update salesforce-aura-objects.txt
  Discovery/Web-Content/api/salesforce-aura-objects.txt
Labels: enhancement

#938 Statistic updater
  .bin/get-and-patch-readme-repository-details.py
  .github/workflows/readme-updater.yml
  README.md
Labels: enhancement
