Repository danielmiessler/SecLists, pull requests merged in 2024-02, with the labels that each got.

#947 openapi.json to Swagger and Api-endpoints lists
  Discovery/Web-Content/api/api-endpoints.txt
  Discovery/Web-Content/swagger.txt
Labels: enhancement

#956 add path link and urls
  Discovery/Web-Content/CMS/wordpress.fuzz.txt
  Discovery/Web-Content/URLs/urls-wordpress-3.3.1.txt
Labels: enhancement

#931 Removed swear words from passwords
  .bin/README.md
  .bin/swear-words-remover.py
  Miscellaneous/list-of-swear-words/README.md
  Miscellaneous/list-of-swear-words/ar.txt
  Miscellaneous/list-of-swear-words/cs.txt
  Miscellaneous/list-of-swear-words/da.txt
  Miscellaneous/list-of-swear-words/de.txt
  Miscellaneous/list-of-swear-words/en.txt
  Miscellaneous/list-of-swear-words/eo.txt
  Miscellaneous/list-of-swear-words/es.txt
  Miscellaneous/list-of-swear-words/fa.txt
  Miscellaneous/list-of-swear-words/fi.txt
  Miscellaneous/list-of-swear-words/fil.txt
  Miscellaneous/list-of-swear-words/fr-CA-u-sd-caqc.txt
  Miscellaneous/list-of-swear-words/fr.txt
  Miscellaneous/list-of-swear-words/hi.txt
  Miscellaneous/list-of-swear-words/hu.txt
  Miscellaneous/list-of-swear-words/it.txt
  Miscellaneous/list-of-swear-words/ja.txt
  Miscellaneous/list-of-swear-words/kab.txt
  Miscellaneous/list-of-swear-words/ko.txt
  Miscellaneous/list-of-swear-words/nl.txt
  Miscellaneous/list-of-swear-words/no.txt
  Miscellaneous/list-of-swear-words/pl.txt
  Miscellaneous/list-of-swear-words/pt.txt
  Miscellaneous/list-of-swear-words/ru.txt
  Miscellaneous/list-of-swear-words/sv.txt
  Miscellaneous/list-of-swear-words/th.txt
  Miscellaneous/list-of-swear-words/tlh.txt
  Miscellaneous/list-of-swear-words/tr.txt
  Miscellaneous/list-of-swear-words/zh.txt
Labels: enhancement

#943 fuzz-b00m-friendly.txt: remove two keywords spotted by WAF
  Fuzzing/fuzz-Bo0oM-friendly.txt
Labels: bug

#944 Add templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
Labels: proposal

#970 Tweak templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement

#971 Misc template tweaks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug

#960 Create keycloak.txt
  Discovery/Web-Content/keycloak.txt
Labels: enhancement

#972 2024.1
  CONTRIBUTORS.md
Labels: enhancement
