Repository danielmiessler/SecLists, pull requests merged in 2024-08, with the labels that each got.

#1045 Add API objects.
  Discovery/Web-Content/api/objects-lowercase.txt
Labels: enhancement

#1053 chore(wordlist): Moved wordlist to its correct directory
  Fuzzing/XSS/robot-friendly/XSS-Fuzzing.txt
Labels: bug

#1054 feat(docs): Added documentation for the 'URI-XSS.fuzzdb.txt' wordlist
  Fuzzing/README.md
Labels: maintenance

#1069 2024.3
  CONTRIBUTORS.md
Labels: enhancement
